version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(ci): "

  - package-ecosystem: gomod
    directory: "/trade-lib"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(trade-lib): "

  - package-ecosystem: gomod
    directory: "/bots"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(bots): "

  - package-ecosystem: gomod
    directory: "/dashboard/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(backend): "
