version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(ci): "

  - package-ecosystem: gomod
    directory: "/core"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(core): "

  - package-ecosystem: gomod
    directory: "/botkit"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(botkit): "

  - package-ecosystem: gomod
    directory: "/bots"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(bots): "

  - package-ecosystem: gomod
    directory: "/dashboard/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(backend): "

  - package-ecosystem: gomod
    directory: "/adapters/bcs"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(adapters/bcs): "

  - package-ecosystem: gomod
    directory: "/adapters/tinvest"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(adapters/tinvest): "
